services:
  - type: web
    name: tasksync-notifications
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        value: tasksync-70aa9
      - key: SMTP_USER
        value: tasksyncscheduler@gmail.com
      - key: SMTP_PASSWORD
        sync: false
      - key: SERVER_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://tasksync-70aa9.web.app
